export const USER_NAME_LABEL = "Your name";
export const USER_NAME_PROPERTY = "username";
export const USER_NAME_PLACEHOLDER = "Username";
export const USER_NAME_VALIDATION_TEXT = "Please input your username!";
export const USER_NAME_DEFAULT_VALUE = "Vasya Vasyliev";
export const EMAIL_LABEL = "Your e-mail";
export const EMAIL_PROPERTY = "email";
export const EMAIL_PLACEHOLDER = "E-mail";
export const EMAIL_VALIDATION_TEXT = "Please input your E-mail!";
export const EMAIL_DEFAULT_VALUE = "Vas_Vasyliev@gmail.com";
export const ARTIST_NAME_LABEL = "Artist name";
export const ARTIST_NAME_PROPERTY = "artist";
export const ARTIST_NAME_PLACEHOLDER = "Artist name";
export const ARTIST_NAME_VALIDATION_TEXT = "Please select artist name!";
export const MESSAGE_LABEL = "Your message";
export const MESSAGE_PROPERTY = "message";
export const MESSAGE_VALIDATION_TEXT = "Please, inter your feedback!";
export const MESSAGE_DEFAULT_VALUE =
         "In writing terms, it suffers from two distinct problems 1. Forcing too much information into too short a space: the result is dense sentences that the reader must spend time unpicking to understand. 2. Artspeak and jargon: it uses a lot of language particular to the discipline of art and therefore contains words and ideas that might not be understood by readers who don’t know art world language and concepts. 4. Unfinished narratives: beginning a story and not finishing it, ie stories hinted at but not told, unexplained gaps in timelines, leaps from an artist’s controversial status to sudden acceptance as establishment figure and so on.";
