export const GET_ARTISTS_REQUEST = "GET_ARTISTS_REQUEST";
export const GET_ARTISTS_SUCCESS = "GET_ARTISTS_SUCCESS";
export const GET_ARTISTS_FAIL = "GET_ARTISTS_FAIL";
export const GET_MUSEUMS_REQUEST = "GET_MUSEUMS_REQUEST";
export const GET_MUSEUMS_SUCCESS = "GET_MUSEUMS_SUCCESS";
export const GET_MUSEUMS_FAIL = "GET_MUSEUMS_FAIL";
export const GET_ARTIST_REQUEST = "GET_ARTIST_REQUEST";
export const GET_ARTIST_SUCCESS = "GET_ARTIST_SUCCESS";
export const GET_ARTIST_FAIL = "GET_ARTIST_FAIL";

export const LOADING_FAILED = "Request failed, please reload page";
export const LOADING = "Loading...";
